# Generated by Django 4.2.10 on 2024-03-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='name',
        ),
    ]
