# Generated by Django 4.2.10 on 2024-03-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='course',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='year_level',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
